### ISSUE TITLE
Step 3 last one: python manage.py migrate

### ISSUE THREAD

**Issue by BruceKilmister** [xushvai/io#5]
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(_args, *_options)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in **init**
    self.loader = MigrationLoader(self.connection)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in **init**
    self.build_graph()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 179, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 133, in ensure_connection
    self.connect()
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/**init**.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/baodongzhang/.local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 471, in get_new_connection
    conn = Database.connect(*_conn_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/**init**.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in **init**
    super(Connection, self).**init**(_args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'Bruce'@'localhost' (using password: YES)")

**Comment by xushvai** [comment]
> django.db.utils.OperationalError: (1045, "Access denied for user 'Bruce'@'localhost' (using password: YES)")

Check your database account.
